### PR TITLE
Add libnetcdf as an explicit dependency

### PR DESCRIPTION
**Pull request by xylar**
This is necessary to make sure the version that gets compiled in
is the same as the one used at runtime.

Add xylar as a maintainer

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@muryanto1, I'm pretty sure this will fix the issue with `cdms2`, `cdtime` and `cdat`.  I think without explicitly pinning libnetcdf, the build was coming in with one version during build (4.7.1) and another version during runtime.  This is one of the reasons it's absolutely critical to have all the dependencies for compiled packages explicitly in the feedstock, not just coming in from other dependencies.  If they're missing, the pinnings can get lost.

**Comment by xylar** [comment]
Once this is merged, I'll issue another PR to build with the conda-forge pinned version, libnetcdf 4.7.1

**Review by muryanto1 — APPROVED** [review]

**Comment by xylar** [comment]
@muryanto1, please merge this unless you know others want to review it

**Comment by xylar** [comment]
Thanks!

**Pull request merged**
