### PR TITLE
rebuild for libnetcdf 4.7.4

### PR DESCRIPTION
**Pull request by muryanto1**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by muryanto1** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@muryanto1, this isn't rebuilding for libnetcdf 4.7.4 yet because the migrator hasn't got this far yet.  I think there must be some dependencies that haven't been built for libnetcdf 4.7.4 yet or the bot just hasn't realized.  In any case, a rerender isn't enough to pick up the new version until all the packages have migrated and it becomes the new pin, which hasn't happened yet.

**Comment by muryanto1** [comment]
@xylar oh, thanks for pointing it out.

**Comment by xylar** [comment]
you can follow the migration at https://conda-forge.org/status/

**Comment by xylar** [comment]
Weird, it looks like the bot glitched somehow and never generated a PR for this feedstock.  @ocefpaf, any idea who we should ask about this?  In the meantime, I'll try to update this PR by manually adding the migrator.

**Comment by xylar** [comment]
It seems like one potential reason for the glitch might be that the bot doesn't have a fork yet.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> Weird, it looks like the bot glitched somehow and never generated a PR for this feedstock. @ocefpaf, any idea who we should ask about this? In the meantime, I'll try to update this PR by manually adding the migrator.

Pinging @beckermr and @CJ-Wright who are way more knowledgeable about the bot's inner guts than me.

**Comment by beckermr** [comment]
Yup @ocefpaf! I looked at a bunch of commits on the graph trying to debug this and I could not figure out why it never happened. We decided to wait for the next migration to see if the bug reappears.

**Comment by ocefpaf** [comment]
Thanks for looking into it!

**Comment by CJ-Wright** [comment]
seems like it thought it didn't need it or that a human did the migration? https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/libdrs_f.json#L142-L160

**Comment by beckermr** [comment]
yep but when I looked at the graph it went from waiting on a dep in one commit to being marked as done by a human on the next. and this happened well before this PR

**Comment by CJ-Wright** [comment]
Hmm, we should try to put more metadata into those fake PRs it would help with the debug.

**Pull request merged**
