### PR TITLE
V3.1.1

### PR DESCRIPTION
**Pull request by dnadeau4**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dnadeau4** [comment]
@CJ-Wright @ocefpaf We still cannot merge this libraries @doutriaux1 and @dnadeau4  are in the maintainers.  We do have write access.

**Comment by dnadeau4** [comment]
https://github.com/orgs/conda-forge/teams/libdrs_f/members?utf8=%E2%9C%93&query=+

**Comment by dnadeau4** [comment]
@conda-forge-admin, please update team

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender¶

**Comment by CJ-Wright** [comment]
Do you still not have commit rights?

**Comment by dnadeau4** [comment]
yes just made a change.

**Comment by dnadeau4** [comment]
@CJ-Wright Can't get that merge button....

**Comment by dnadeau4** [comment]
My last issue worked! Thanks @CJ-Wright

**Pull request merged**
