### PR TITLE
recompile and rerender

### PR DESCRIPTION
**Pull request by dnadeau4**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
Why can't I merge this PR?

**Comment by dnadeau4** [comment]
@ocefpaf Could you verify why this PR is not merged?  I ran `conda-smithy` and all, could be the same issue with circleci we had before.

**Comment by ocefpaf** [comment]
> Why can't I merge this PR?

You should be able to b/c you are listed as a maintainer :-/
Maybe check your GitHub notifications, you may have missed the invitation to the feedstock. Meanwhile I'll merge this for you.

**Comment by dnadeau4** [comment]
@ocefpaf I think we created a discrepancy between `conda-forge` and `conda-forge-admin` when we recreated `libdrs_f-feedstock` here. 

https://github.com/conda-forge/staged-recipes/pull/6930

These are now different. (`conda-forge-admin` and `conda-forge`)

https://github.com/conda-forge-admin/libdrs_f-feedstock/blob/master/recipe/meta.yaml
https://github.com/conda-forge/libdrs_f-feedstock/blob/master/recipe/meta.yaml

I checked my notifications and everything is ok on that side.   Not sure how to fix this,  and I wonder if the `bot` will be able to push updates. 

Thanks for merging this!! 😄

**Comment by ocefpaf** [comment]
> I checked my notifications and everything is ok on that side. Not sure how to fix this, and I wonder if the bot will be able to push updates.

The bot should be OK. Pinging @CJ-Wright here for awareness.

>  checked my notifications and everything is ok on that side.

Let's try to update the team and see if that fixes the permissions here.

**Comment by dnadeau4** [comment]
ok thanks!

**Pull request merged**
