### PR TITLE
fix UV-CDAT-> CDAT

### PR DESCRIPTION
**Pull request by dnadeau4**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
@ocefpaf Could you verify why "master" cannot upload this fie?  It compiled fine but `anaconda upload` failed.  I went in circleci and the file does exist.  

https://circleci.com/gh/conda-forge/libdrs_f-feedstock/42

**Comment by ocefpaf** [comment]
@dnadeau4 #14 should fix it. I'm restarting the CIs now.

**Comment by ocefpaf** [comment]
Actually, #14 did not fix it :-(

I'm taking a closer look at this. Hold on...

**Comment by dnadeau4** [comment]
@ocefpaf thanks!

**Pull request merged**
